# Why use NumPy?
Arrays use less memory (thus more efficient) than standard Python arrays at the cost requiring homogeneous arrays.

First, let's import numpy

In [1]:
import numpy as np

# Arrays
The __rank__ of an array is the number of dimensions and the __shape__ is a tuple of integers giving the size of the array along each dimension.

We start off with basic arrays (note, the basic type is a `np.float64` but we can change this using `dtype = np.int64`, etc. ):
- array
- zeros/ones
- arange
- linespace

Indexing and Slicing are done like normal

In [43]:
a1 = np.array([1, 2, 3, 4, 5, 6])
a2 = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(a1, "of size", a1.shape)
print(a2, "of size", a2.shape, "(i.e. 3 elements of 4 elements each)")
print("We index and slice the array like normal", a2[2][2])
print("-----------")
# We can also easily create an array filled with 0's or 1's.
zeros = np.zeros(3)
ones = np.ones(4)
print(ones)
print("-----------")
# We can also create an array with a range of elements
rang = np.arange(4)
print(rang)
rang = np.arange(2, 9, 2) #start, end, step_size
print(rang)
# Instead of specifying a step size, we can take a selected number of uniform steps between 2 points (inclusive of start & end)
uniform = np.linspace(2, 10, 5)
print(uniform)

[1 2 3 4 5 6] of size (6,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] of size (3, 4) (i.e. 3 elements of 4 elements each)
We index and slice the array like normal 11
-----------
[1. 1. 1. 1.]
-----------
[0 1 2 3]
[2 4 6 8]
[ 2.  4.  6.  8. 10.]


# Getting Array Info

In [34]:
a1 = np.array([1, 2, 3, 4, 5, 6])
a2 = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print("Size:", a2.size)
print("Dimensions:", a2.ndim)
print("Shape:", a2.shape)

Size: 12
Dimensions: 2
Shape: (3, 4)


# Adding, Removing and Sorting Elements

We can sort using `np.sort(array)`
We can concatenate using `np.concatenate(a1, a2)`

In [35]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b)))
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(np.concatenate((x,y), axis = 0))

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]


# Reshaping an Array

We can reshape with `arr.reshape(rows, columns)`

In [41]:
a = np.arange(6)
print(a)
print("We can now reshape this array by specifying the number of rows and columns we want (# elements must remain the same): ")
b = a.reshape(3, 2)
print(b)

[0 1 2 3 4 5]
We can now reshape this array by specifying the number of rows and columns we want (# elements must remain the same): 
[[0 1]
 [2 3]
 [4 5]]


# Subsets of Array
We can get a subset of an array without using loops!

In [46]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


We can even create a boolean array and use that to index an array based on some condition

In [50]:
five_up = (a >= 5)
print(five_up)
print(a[five_up])
divisibleBy2 = (a%2 == 0)
print(a[divisibleBy2])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


We can use `&` and `|` to combine operations

In [52]:
c = a[(a>2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


We can be even more complex and create coordinates using `zip` and `list` (list is needed to transform object into list)

In [60]:
b = np.nonzero(a < 7)
print(b)
print("This returns a tuple of arrays. The first is the row indices of where the values are found, the second is the column indices")
list_of_coordinates = list(zip(b[0], b[1]))
for i in list_of_coordinates:
    print(i)

(array([0, 0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 3, 0, 1], dtype=int64))
This returns a tuple of arrays. The first is the row indices of where the values are found, the second is the column indices
(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)


# Basic Array Operations

Basic Math

In [67]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)
print(data - ones)
print(data * ones)
print(data / ones)
print(sum(data))

[2 3]
[0 1]
[1 2]
[1. 2.]
3


When it comes to 2D arrays we would have to specify the axis to sum over

In [78]:
b = np.array([[1,2], [4,5]])
print(b)
print(b.sum(axis = 0)) #down columns
print(b.sum(axis = 1)) # across rows

[[1 2]
 [4 5]]
[5 7]
[3 9]
